version: "3.9"

services:
  wordpress:
    build: .
    container_name: wordpress
    volumes:
      - wordpress-files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${SERVICE_USER_WORDPRESS}
      WORDPRESS_DB_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS}
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 5s
      timeout: 10s
      retries: 5

  mariadb:
    image: mariadb:11
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_ROOT}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${SERVICE_USER_WORDPRESS}
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 20s
      retries: 5

volumes:
  wordpress-files:
  mariadb-data:
